### ISSUE TITLE
Unicode EXCLUDED_FOLDERS not supported

### ISSUE THREAD

**Issue by and7ey** [trickortweak/flickr-uploader#23]
If I define Unicode value in EXCLUDED_FOLDERS list:

```
EXCLUDED_FOLDERS = ["@eaDir",u"что-то на русском"]
```

Then I get the following warning - 

> uploadr.py:452: UnicodeWarning: Unicode equal comparison failed to convert both arguments to 
> Unicode - interpreting them as being unequal
>  if curr_dir in dirnames:

**Comment by oPromessa** [comment]
This particular feature is available on the forked tool:
- [The GituHub repository is oPromessa/flickr-uploader](https://github.com/oPromessa/flickr-uploader)
- [Available via pypi.python.org on this link](https://pypi.org/project/flickr-uploader)

@and7ey Let us know if you still have any issue.
