### ISSUE TITLE
Upload when lots of files

### ISSUE THREAD

**Issue by BaesFr** [trickortweak/flickr-uploader#33]
Is it possible to write a log file that we can check periodically to control that upload is ok ?

Because i launch it in a NAS, I have not the console return. 

I think it can be possible to write a log file in the same directory and we can open it.

IF (and only if) possible something like this will be perfect.

2014-12-03 09:00 Start uploading
2014-12-03 09:01 [ ] file_1.jpg

later
2014-12-03 09:00 Start uploading
2014-12-03 09:01 [OK] file_1.jpg
2014-12-03 09:02 [OK] file_2.jpg
2014-12-03 09:03 [FAILED] file_3.jpg
2014-12-03 09:04 [OK] file_4.jpg
2014-12-03 09:05 [UPLOADING] file_4.jpg

or better if think of something else

And perhaps an estimated time of arrival ?

Thanks a lot

**Comment by lodoss5** [comment]
Thanks davidjb for your answer but with this solution, log file is updated only at the end of the execution or am I missing something?

**Comment by davidjb** [comment]
@lodoss5 Redirection via ``>>`` will stream the terminal output into the given file, as it would have otherwise been echoed to the screen; no buffering will take place since the logging is just via ``print`` statements in the Python code.

**Comment by lodoss5** [comment]
@davidjb I have a scheduled task (/volume1/@appstore/python/bin/python /volume1/tools/flickr-uploader/uploadr.py >> /volume1/tools/flickr-uploader/log.txt) and it only writes in the log file once finished, what am I missing?

**Comment by evanjardineskinner** [comment]
I have found the synology box does tend to buffer quite a bit of output before it writes to a file. Certainly if I run uploadr.py with nohup that is true anyway. I would have expected you to see something before the code completes completely though, unless the output is fairly short, in which case the synology OS might be not have exhausted its output buffer before you code completes.

**Comment by oPromessa** [comment]
Try this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als](https://pypi.org/project/flickr-uploader/).

* stdout and stderr output is available.
* also a rotating log mechanism can be setup (not to consume too much disk space)
* Synology does send you feedback via email (if configured!). check the sample uploadr.cron file which you can use.
* much more logging is available.

**Comment by oPromessa** [comment]
I'm closing this topic due to lack of activity. @BaesFr let us know should you have any further queries.
