### ISSUE TITLE
Error PIL

### ISSUE THREAD

**Issue by Kutufluix** [trickortweak/flickr-uploader#39]
Hello!

I have been trying to use your script on my Synology NAS but when i try to run it i always get the following error:

 File "./uploadr.py", line 75, in <module>
    from PIL import Image
ImportError: No module named PIL

I guess i need to install something else that includes that PIL module?
Btw i'm using Python 2.7.8-11

Thanks

**Comment by Kutufluix** [comment]
I found the solution, i needed to:

- Install bootstrap for my NAS model
- install ipkg
- install the PIL module

solved!

**Comment by lodoss5** [comment]
Hi,

This script is supposed to work with SynoCommunity Python package without any modifications, please be sure to use it in your command line.
Here is mine:  /volume1/@appstore/python/bin/python /volume1/tools/flickr-uploader/uploadr.py

Regards

**Comment by lodoss5** [comment]
Anyway PIL import has been removed thanks to davidjb :)
