### ISSUE TITLE
Invalid auth token

### ISSUE THREAD

**Issue by Flavien06** [trickortweak/flickr-uploader#40]
Hi
When I launch the script I have this error
I have created my API key and entered the .ini
an idea?
Thank

>Flav> /usr/local/python/bin/python /volume1/homes/Flavien/Script_Synology/
flickr-uploader/uploadr.py
--------- Start time: Sun Mar  8 12:52:49 2015 ---------
Setting up the database: /volume1/homes/Flavien/Script_Synology/flickr-uploader/flickrdb
Completed database setup
Error: {u'stat': u'fail', u'code': 98, u'message': u'Invalid auth token'}
Getting new token
Copy-paste following URL into a web browser and follow instructions:
https://api.flickr.com/services/auth/?perms=delete&api_key=**********my*api*key*********&frob=************-************-*******&api_sig=***********api*sig*********
Have you authenticated this application? (Y/N): y
Error: {u'stat': u'fail', u'code': 108, u'message': u'Invalid frob'}
*****Removing empty Sets from DB*****
*****Completed removing empty Sets from DB*****
*****Adding Flickr Sets to DB*****
{'nojsoncallback': '1', 'format': 'json', 'perms': '', 'auth_token': 'None', 'api_sig': '***********api*sig*********', 'api_key': '**********my*api*key*********', 'method': 'flickr.photosets.getList'}
Error: {u'stat': u'fail', u'code': 98, u'message': u'Invalid auth token'}
*****Completed adding Flickr Sets to DB*****
*****Uploading files*****
Found 22870 files
Uploading /volume1/photo/10428478_10204171196951004_5819615984709327482_n.jpg...
A problem occurred while attempting to upload the file: /volume1/photo/10428478_10204171196951004_5819615984709327482_n.jpg
Error: <?xml version="1.0" ?><rsp stat="fail">
        <err code="98" msg="Invalid auth token"/>
</rsp>
Uploading /volume1/photo/Avatar/10441450_10203764318379294_1797068429541299508_n.jpg...
A problem occurred while attempting to upload the file: /volume1/photo/10441450_10203764318379294_1797068429541299508_n.jpg
Error: <?xml version="1.0" ?><rsp stat="fail">
        <err code="98" msg="Invalid auth token"/>
</rsp>
Uploading /volume1/photo/1498979_10203761372865658_6794724194913341457_o.jpg...

**Comment by lodoss5** [comment]
Hi,

Do you have a ".flickrToken" file created by the script? Try deleting it and relaunch script.

**Comment by Flavien06** [comment]
Yes it is good, I have delete .flickrToken, .flickrlock and flickrdb
Thank you
