### ISSUE TITLE
Cannot get token

### ISSUE THREAD

**Issue by yelch** [trickortweak/flickr-uploader#42]
Each time I enter the computed url I land on a github page saying 404

https://github.com/dan-coulter/phpflickr/tools/auth/auth.php?frob=xxxxxxxxxx

How can I create the token?

**Comment by lodoss5** [comment]
So you are running script, it asks you to copy-paste the URL in a browser and you get this error when you do?
Have you verified your key and secret values in ini file? Try using new ones maybe?

**Comment by yelch** [comment]
Tnx for the fast reply.
I think the error was related to the old auth I've tried to reactivate. I've requested a new api key. The URL from the script worked and it's now authorized. After adjusting the ini I still have a 'Invalid token' message and a new .flickrToken with content 'None'

**Comment by lodoss5** [comment]
Are you sure .flickrToken is new? Try deleting .flickrlock and .flickrToken and rerun script.

**Comment by yelch** [comment]
yep tried that. removed them. and they have been recreated after running the script.
.flickrLock is empty and .flickrToken contains 'None'

**Comment by lodoss5** [comment]
Can you show us the messages during the execution of the script?

**Comment by yelch** [comment]
still the same:

--------- Start time: Tue Mar 10 14:46:31 2015 ---------
Setting up the database: ./flickrdb
Completed database setup
Getting new token
Copy-paste following URL into a web browser and follow instructions:
https://api.flickr.com/services/auth/?perms=delete&api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXX&frob=YYYYYYYYYYYYYYYYY-YYYYYYYYYYYYYYYY-YYYYYY&api_sig=ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
Have you authenticated this application? (Y/N): ^C(<type 'exceptions.KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x40dd3b48>)
Error: {u'stat': u'fail', u'code': 108, u'message': u'Invalid frob'}
*****Removing empty Sets from DB*****
*****Completed removing empty Sets from DB*****
*****Adding Flickr Sets to DB*****
{'nojsoncallback': '1', 'format': 'json', 'perms': '', 'auth_token': 'None', 'api_sig': 'a87921fe94ef094e1065a2e8a5d810a7', 'api_key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXX', 'method': 'flickr.photosets.getList'}
Error: {u'stat': u'fail', u'code': 98, u'message': u'Invalid auth token'}
*****Completed adding Flickr Sets to DB*****
*****Uploading files*****

**Comment by yelch** [comment]
just saw that the api_sig from the first call is not the same like the one in the response.... does this matter?

**Comment by lodoss5** [comment]
api_sig must be an md5 hash, so if you don't change your key or secret, it should remain the same I think.

**Comment by yelch** [comment]
I've added a few debug prints under getFrob:
        sig = self.signCall( d )
        print("***var sig=" + sig)
        url = self.urlGen( api.rest, d, sig )
        print("***var url=" + url)
        try:
            response = self.getResponse( url )
            if ( self.isGood( response ) ):
                FLICKR[ "frob" ] = str(response["frob"]["_content"])
                print("*** var response = " + response)

This is the output:
--------- Start time: Tue Mar 10 15:05:27 2015 ---------
Setting up the database: ./flickrdb
Completed database setup
Error: {u'stat': u'fail', u'code': 98, u'message': u'Invalid auth token'}
Getting new token
***var sig=[MYSIG]
***var url=https://api.flickr.com/services/rest/?api_sig=[MYSIG]&api_key=[MYKEY]&nojsoncallback=1&method=flickr.auth.getFrob&format=json
Error: cannot get frob:(<type 'exceptions.TypeError'>, TypeError("cannot concatenate 'str' and 'dict' objects",), <traceback object at 0x40dd5d78>)
Copy-paste following URL into a web browser and follow instructions:
https://api.flickr.com/services/auth/?perms=delete&api_key=[MYKEY]&frob=[MYFROB]&api_sig=[MySig2]
Have you authenticated this application? (Y/N): n
*******************************************************************************
Executing the URL seems to work:
https://api.flickr.com/services/rest/?api_sig=[MYSIG]&api_key=[MYKEY]&nojsoncallback=1&method=flickr.auth.getFrob&format=json
--> I'm no so familiar with python: What is the string-conversion for? How shall I change it?

**Comment by lodoss5** [comment]
Try replacing
                print("*** var response = " + response)
with:
                print("*** var response = " + str(response))

**Comment by yelch** [comment]
sorry for the last message... this was my mistake, but I found now the error:
in "def getToken( self )" the call "res = self.getResponse( url )" results in error
Error: {u'stat': u'fail', u'code': 108, u'message': u'Invalid frob'}
I've compared all frobs, they are the same. Also if I exec the the called url manually the result is the same:
{"stat":"fail","code":108,"message":"Invalid frob"}

**Comment by lodoss5** [comment]
From Flickr website :
     108: Invalid frob
     The specified frob does not exist or has already been used.
Can you try one more time the whole process:
- get your access on http://www.flickr.com/services/apps/create/apply 
- put key and secret in ini file
- launch script
- when script display the URL, copy-paste it in a browser and wait the validation
- then click Y to continue the script

**Comment by yelch** [comment]
This is exactly what I did twice today...

**Comment by lodoss5** [comment]
Can you show the page given by the URL returned by the script?

**Comment by lodoss5** [comment]
I don't know what is the issue.
Removing .flickrlock, .flickrToken and flickrdb files, running script, revalidating via the URL given, then clicking Y in the script, does the job (token file is updated from None to valid value).

**Comment by yelch** [comment]
Wow. I don't know what happened, but I've retried today 5 or 6 times and suddenly it worked! Thank you for the fast support!

P.S.
Another exclude would for the ini be "$RECYCLE.BIN"
