### ISSUE TITLE
Use last modified timestamp to improve checking time

### ISSUE THREAD

**Issue by evanjardineskinner** [trickortweak/flickr-uploader#46]
I've changed my copy of uploadr.py to check last modified and only compute the md5sum if the last modified is different from the one in the db. This improves to time taken to check if any photos are new by a factor of around 3 (bit disappointed it wasn't a bigger difference to be honest but I do have some photos that fail to upload each time so they may be skewing my results). It also means near zero activity on the disk, so less heat and wear and tear etc.

The last modified column is added only if it is not there. The first run through will do md5sum and create the last_modified timestamp and then future runs will check it and only do the md5sum if it is different.

If you can add me as a contributor I can merge the change in.

**Comment by evanjardineskinner** [comment]
OK the last modified change only halved the execution time from 30 minutes to 15 minutes for 17,000 odd photos but I have also added a couple of indexes and now have 15 minutes down to 45 seconds, so that is definitely an optimization worth having :-) I can run this script every night now to ensure my photos are always up to date

**Comment by trickortweak** [comment]
Could you create a pull request for your changes so we can look them over?

**Comment by evanjardineskinner** [comment]
No that I've looked up what a pull request is (not used git before really), yes that sounds like a very good idea. I'll sort that out and let you know. Thanks.

**Comment by trickortweak** [comment]
I merged your pull request. Closing issue.

**Comment by evanjardineskinner** [comment]
Awesome. Thanks for the speedy replies and action!
