### ISSUE TITLE
BBE128

### ISSUE THREAD

**Issue by lodoss5** [trickortweak/flickr-uploader#48]
Message from BBE128 recreated as new issue:

Hi all,
This script seems to be able to do what I've been looking for.
However, I'm not familiar with scripts or programming (only in vba and in SPSS).

If I understand well, the first part of the uploadr.py is only comment, starting and ending with """". So the real script starts with: import sys
After all the import there is an instruction to read the .ini file by the command config.read(os.path...etc.
Do I understand well that the only changes I need to make are inside that .ini file?

I understand to replace YourDir, YourKey and YourSecret.
But then further down I think I do not understand what exactly I need to change in the script to personalize it. Or maybe there is no need to change anything anymore?
There is the line DB_PATH = os.path.join(os.path.dirname(sys.argv[0]), "flickrdb").
Does the system know what this "flickrdb" is, or do I have to write my path here? I'm confused because this doesn't seem to refer to the initially defined FILES_DIR.
The same goes for ".flickrlock" and ".flickrToken". And why are these preceeded by a dot, in contrast to "flickrdb"?
Finally, the RAW_TOOL_PATH = "/volume1/photo/Image-ExifTool-9.69/" suggests that I need to install the ExifTool. And shouldn't I personalize the path then?

Finally, do I need to put these 2 files within the Python directory, or is that not important?
I ran the script (I only changed YourKey, YourDir etc) - at least I think - but nothing happended.
So I'm trying to figure out what I'm doing wrong.

I hope someone will clarify this to me (and maybe many others).
Sorry for these dumb questions. But thanks for reading. And hopefully: thanks for useful answers!

**Comment by lodoss5** [comment]
Hi,
You just have to edit YourDir, YourKey and YourSecret.
You don't have to put the 2 files in your python dir.
If nothing happened then you must have an issue concerning how to run the script.
Try using full path to your python exe and full path of the script, like this:
          /usr/local/python/bin/python /volume1/script/flickr-uploader/uploadr.py
At least there must be some lines displaying script is running or failing.

**Comment by BBE128** [comment]
Okay, thanks for your reply, the first part is clear.
I agree that it seems likely to be an issue with running the script.
I don't understand what to do with "using full path to your python exe". How do I actually open python? Do I need to open it? When I double click on the python.exe file (stored on the NAS), synology wants to upload it to my PC. Using an option from the Action button from the top menu doesn't do it either. When I try to start the file uploadr.py, the system searches an application on my PC (which results in an error), not on the NAS.
So, how to continue?

**Comment by BBE128** [comment]
I found what you meant. In Task planner I changed the script.
It read like this: /volume1/Download/Flickr uploader/uploadr.py
I changed it to: /usr/local/python/bin/python /volume1/Download/Flickr uploader/uploadr.py  or to:
python /volume1/Download/Flickr uploader/uploadr.py or
/usr/bin/python /volume1/Download/Flickr uploader/uploadr.py
After clicking on Run nothing happens....

**Comment by lodoss5** [comment]
Don't use space in your path, it will be easier to handle.
Use "Flickr-uploader" instead of "Flickr uploader".
After this, cliking on Run should take your CPU to 100% and upload files but you won't see anything graphical.
If you want to see what happened you have to redirect output to a file like this:
/usr/local/python/bin/python /volume1/Download/Flickr-uploader/uploadr.py >>/volume1/Download/Flickr-uploader/log.txt

But 1st of all, you have to run it via a command line tool like WebConsole (there is a package on http://packages.missilehugger.com) or via a ssh terminal (like Putty or Kitty) to get the token file.
Launch WebConsole (put admin/admin as login/password) or your ssh terminal software then put:
/usr/local/python/bin/python /volume1/Download/Flickr-uploader/uploadr.py

It will run the script and script will ask you to open an URL...

**Comment by BBE128** [comment]
Nice fast reply.
The second part I don't understand. The link is offline, but found it on google.
Why doesn't synology have that in its system?
Do I need a token file, apart from the uploadr.ini and uploadr.py files?
And I was thinking, do I need to authorize traffic somewhere?

**Comment by lodoss5** [comment]
Synology does not have a Web browser. Token file will be generated by the script once you will validate the url in a browser on chrome, Firefox, safari... No need to authorize traffic, it will be done via http.

**Comment by BBE128** [comment]
Which username and password do I need to feel in? It's the login into what?
Why isn't it mentioned in the instructions of installation of the uploadr.py that you need a webbrowser program? Is this safe?

**Comment by lodoss5** [comment]
It is not specified in the installation instructions of the script because it is asked during the first run of the script, not installation.
If URL asks you a login and password I guess it should be the credentials of your Flickr account.
If you think it is not safe, trust your browser, it should validate the site as to be the real Flickr website, else you still have the choice to create new flickr account for test purpose, ask api_key and secret... etc...

**Comment by BBE128** [comment]
Thnx for your patience and your help so far.
But I just don't get it.
I've installed webconsole on the Synology drive.
I've opened the file webconsole.php in the synology text editor and changed username, password and path, for the last one I filled in /usr/local/python/bin/python /volume1/Download/Flickr-uploader/uploadr.py.
I've saved the file.
When I double click it, the file wants to be saved on my PC. The other option is through the Action button at the top to open it in a new browser tab. But what next? I don't understand how the URL would ask for the username and password...

**Comment by lodoss5** [comment]
You are on the wrong way with Webconsole install, it is a package with a ui like other synology package. Please Follow this tuto: http://missilehugger.com/708/synology-package-web-console/

**Comment by lodoss5** [comment]
But if I remember correctly, sorry I jut remember now... Webconsole may not be the solution for the first run. Install a ssh client instead on your computer, like kitty http://www.9bis.net/kitty/
You will have to enable ssh on your synology also

**Comment by lodoss5** [comment]
Then log to your synology using kitty with your login/password of your synology. Then you will have access to the command line in ssh and you will be able to run the Flickr upload script.

**Comment by BBE128** [comment]
okay, step by step. 
Kitty installed om my PC. I managed to logon to synology (somewhat confusing initially that giving in of the password wasn't shown. but after Enter I got in).
Then it gives DiskStation>
Then I have to fill in the path, obviously. Probably in the wrong format, because none of the paths I entered will do. I tried the full length (/usr/local/python/bin/python /volume1/Download/Flickr-uploader/uploadr.py) as well as the shorter one (/volume1/Download/Flickr-uploader/uploadr.py), with slashes as well as back slashes.

**Comment by lodoss5** [comment]
First, just try to enter "/usr/local/python/bin/python", it should give:
<b>Python 2.7.10 (default, Jun  3 2015, 13:42:00)
[GCC 4.6.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
  \>>> </B>
Use "Ctrl-D" to quit python program.

Then try to locate the script with "cd /volume1/Download/Flickr-uploader" (to change current directory) then "ls" (to list content of the current directory). UNIX system is case sensitive so make sure to enter correct commands.
If it says: "can't cd to /volume1/Download/Flickr-uploader" then try "cd /volume1/Download" then do a "ls" to see what is the content...etc...

**Comment by BBE128** [comment]
I entered "/usr/local/python/bin/python", then it gives this:
-sh: /usr/local/python/bin/python: not found

When I entered "/usr" then it gives
-sh: /usr: Permission denied

**Comment by lodoss5** [comment]
Which python did you installed? The one from synology or from synocommunity? And which version? 2 or 3?

**Comment by BBE128** [comment]
version 2.7.6
I installed it in May 2014, long before I started trying to use it. Don't remember where I got it from.
I checked the package centre, which shows that Python module and Python 3 are not installed. So I guess I got it somewhere else.
Should I install these both?

**Comment by BBE128** [comment]
I installed Python 3 form the package centre.
"/usr/local/python/bin/python" still gives: not found

**Comment by lodoss5** [comment]
Please install official Python 2 from Synology, this is the one which will be installed in "/usr/local/python"

**Comment by BBE128** [comment]
There is no Python 2 in the Package centre, only a Python module. Says to be an extension for Python 2.
is there another to install it?

**Comment by lodoss5** [comment]
Python module is the v2.

**Comment by BBE128** [comment]
Already installed that one.
Giving in the line "/usr/local/ etc in kitty has the same result: not found. ...

**Comment by BBE128** [comment]
I tried the list command with ls. It give #recycle  Cloudstation ReferenceManager (the last one is a bibliographic program). But I don't recognize why these 3 are listed, for they don't seem to be in one and the same directory, especially not in Volume1 top root.

**Comment by lodoss5** [comment]
By default in kitty, current directory is your home directory. 
Weird I thought official Python was the one in the path I gave u. Try install the python from synocommunity. You can add this 3rd party repository via this tuto : https://synocommunity.com/#easy-install

**Comment by lodoss5** [comment]
This new Python should install in /volume1/@appstore/python/bin/python

**Comment by BBE128** [comment]
I read about Linux, very informative about linux structure on http://www.thegeekstuff.com/2010/09/linux-file-system-structure/ . How do I find out where files are stored? Or is this by default? Obviously in the Synology explorer most directories are not shown. Anyway to get in there? Just curious, probably it's not necessary for me now.
I'll install the Python form the link you suggested.

**Comment by lodoss5** [comment]
Python will install in the path it is supposed to be, this is default, you cannot choose, but I guess it depends of what kind of Synology you have because all package arch are not the same.
Mine is DS213, so package version is 88f6282. See this for more details: http://forum.synology.com/wiki/index.php/What_kind_of_CPU_does_my_NAS_have
To get access to full filesystem, you have to use ssh client or Webconsole.
I am not sure if this command works on Synology but via ssh you can try to use "whereis python", it should display where python is.

**Comment by BBE128** [comment]
okay, I've installed Synocommunity, which is now visible under a new tab in Package center. 
There are several Python programs, and I took "Python", not Python3.
With Kitty I managed to enter Python as you described, then I changed directory. Still going well.
With ls all files in that directory are summorized, among which the uploadr.py.
Then I entered /usr/local/python/bin/python /volume1/Download/Flickr-uploader/uploadr.py , but then I get: -sh: usr/local/python/bin/python: not found
I'm probably in the wrong directory, but I'm not familiar with DOS commands, don't know how to do this the right way.

**Comment by lodoss5** [comment]
This is not DOS but UNIX commands.
You don't have to be in the right directory since you indicate full path.
Enter the correct syntax starting with the "/" prior to "usr" (the error message indicates you forgot it):
/usr/local/python/bin/python /volume1/Download/Flickr-uploader/uploadr.py

**Comment by BBE128** [comment]
Okay, probably I did wrong. Now a little step further, after entering that path it says:
  File "/volume1/Download/Flickr-uploader/uploadr.py" line 6
     <!DOCTYPE html>
SyntaxError: invalid syntax

Is something wrong in my uploadr.py file?

**Comment by lodoss5** [comment]
Line 6 does not look like "<!DOCTYPE html>", can you download one more time the uploadr.py file?

**Comment by BBE128** [comment]
![kitty flickruploadr](https://cloud.githubusercontent.com/assets/12831686/8337058/f541ef48-1aa8-11e5-8046-9a8c2e35598e.JPG)

I had an older version (sorry). After updating the file still gave an error, see screen capture.

**Comment by lodoss5** [comment]
Have you updated your ini file with latest version also?

**Comment by BBE128** [comment]
I did that too, thought I already had but obviously I hadn't.
Then it finally ran.
Got a problem with the instruction to copy the line with the url, because when I copied the script was interrupted. Then did it again but copied the url by typing. And answered Y.
I got the token etc, which are now as small files in the same directory.
I saw it reading the 2 files in the test directory, but when I checked in Flickr, that directory has not been turned into a new album.
Kitty gave some lines I don't understand, see screenshot
![kitty flickruploadr 2](https://cloud.githubusercontent.com/assets/12831686/8340131/ac2407ba-1abc-11e5-9936-4787bb7863c3.JPG)
I'm getting close now....

**Comment by BBE128** [comment]
not true!
login out of Flickr and back in again the album was there. Now I'm gonna try with the real albums...
Thanks a lot for all your patience and help!
I hope some other people will be glad with these detailed instructions too.

**Comment by BBE128** [comment]
A final (maybe?) question about the script. If tags of a photo are changed, will these changes be transported to the photo on flickr (or vice versa if tags in Flickr are changed, will these be transported to the photo on the Synology drive)?

**Comment by lodoss5** [comment]
I am glad this is finally working. I don't think tags will be updated.
