### ISSUE TITLE
Feature request: Dissable option to delete flickr pictures

### ISSUE THREAD

**Issue by snoopy86** [trickortweak/flickr-uploader#50]
Would be good if we could dissable that photos are deleted from flicker when you delete them from local disk (accidentally).

**Comment by egikyan** [comment]
You can achieve this pretty easy - just comment out lines 345 to 369 and line 1021.

**Comment by vinzz73** [comment]
The line numbering has changed since. It is now 344 to 368, line 1021 I am not sure of which line it corresponds to in todays script.

Beter solution would be to include a true/false option.

**Comment by oPromessa** [comment]
Try this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als]o(https://pypi.org/project/flickr-uploader/). It includes the option `-no-delete` and also tags such pics for eas=y searching manipulating within Flickr.

**Comment by oPromessa** [comment]
I'm closing this topic. @snoopy86 let us know if you have any more questions on this.
