### ISSUE TITLE
Feature Request: Possibility to crypt file before upload

### ISSUE THREAD

**Issue by gborri** [trickortweak/flickr-uploader#52]
Using flickr as a backup storage, i think is useful to crypt file before uploading in order to preserve privacy.

**Comment by Grinderz** [comment]
if you try to upload encrypted files, flickr return error code 5, Filetype was not recognised.

**Comment by oPromessa** [comment]
Additionally, isn't the upload already performed via HTTP

`
netstat -tc -p -v -W -o | egrep "python|yahoo|flickr"

tcp        0      0 192.168.1.43:53347      r2.ycpi.vip.ams.yahoo.net:https ESTABLISHED 29351/python2.7      off (0.00/0/0)
`

**Comment by Grinderz** [comment]
yeah upload do via secure layer since 646a400e9c274e41d8a9fff22915a208c3b7d48f.
but i meen seems not posible store encrypted file on flickr side.
