### ISSUE TITLE
Syntaxerror: invalid syntax

### ISSUE THREAD

**Issue by cipo80** [trickortweak/flickr-uploader#55]
Hi guys, first of all thanks for this great free script!

I'm trying to configure it for the first time, but i don't understand where is the error.
I've download the latest release by github project home (June 2015) edit the .ini file with the path directory:  FILES_DIR = “/volume1/photo/test“
I've put the key and the secret generated by Flickr web procedure and i don't have touch anything else inside the .ini file.
I've put the upload.py and .ini file into a dedicated new folder called "script" with read/write permissions for the admin user and the i've run the script in ssh by admin user.
Reading other answer issues here in github i've try to launch the script using the full path, but i receive always this syntax error:

nas> /usr/local/python/bin/python /volume1/script/flickr-uploader/uploadr.py
Traceback (most recent call last):
  File "/volume1/script/flickr-uploader/uploadr.py", line 91, in <module>
    FILES_DIR = eval(config.get('Config','FILES_DIR'))
  File "<string>", line 1
    “/volume1/photo/test“
    ^
SyntaxError: invalid syntax

Thank for any help!

**Comment by lodoss5** [comment]
Hi,

Your issue seems to come from the ini file, line:
FILES_DIR = "YourDir"

Check the double quotes character, line should be:
FILES_DIR = "/volume1/photo/test"

**Comment by cipo80** [comment]
Hi lodoss5 and thank you for the reply!

The files_dir path it's correct with the double quotes, but i've just solve the issue i'm starting from 0, re-download the .ini edit the files_dir and the key rows and now it's working!
I don't understand why, but probably some mistake with text edit in some rows..anyway thank you again also for this great job!

**Comment by lodoss5** [comment]
Great, enjoy :)
