### ISSUE TITLE
Script doesnt proceed with non-ascii chars in FILES_DIR target

### ISSUE THREAD

**Issue by Wesalius** [trickortweak/flickr-uploader#56]
I had hard time solving why script would not localize my photos. Finally I renamed the folder whcih I targeted with FILES_DIR from "Jonáš" tu "Jonas" and that resolved this bug. If you aint gonna add non-ascii chars support to the script, please warn future users about naming conventions in the Installation requirements.

**Comment by oPromessa** [comment]
Try this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als]o(https://pypi.org/project/flickr-uploader/). It should handle international characters nicely.

**Comment by oPromessa** [comment]
Closing this topic. @Wesalius, let us know in case it's not solved.
