### ISSUE TITLE
found 0 files

### ISSUE THREAD

**Issue by gitdex** [trickortweak/flickr-uploader#58]
Hello 
I got the script running but i wont find any files, please advice if possible.

[Config]
###### 
# Location to scan for new files
###### 

FILES_DIR = "/volume1/photo/Billeder alle år/2004 Sverige sommer/"
###### 
# Flickr settings
###### 
# Set your own API key and secret message
# Go to http://www.flickr.com/services/apps/create/apply and apply for an API key
# 

FLICKR = {
        "title"                 : "",
        "description"           : "",
        "tags"                  : "auto-nasupload",
        "is_public"             : "0",
        "is_friend"             : "0",
        "is_family"             : "0",
        "api_key"               : "x",
        "secret"                : "y"
        }

**Comment by lodoss5** [comment]
Hi,
Can you show us the result of the execution?
Can you try with a less complex path, like FILES_DIR = "/volume1/photo/test"

**Comment by gitdex** [comment]
thank you for quick reply. I change folder name to one without "Å" and now i works..

**Comment by oPromessa** [comment]
Try this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als]o(https://pypi.org/project/flickr-uploader/). It should handle International characters nicely both in folders and filenames.

**Comment by oPromessa** [comment]
Closing this issue for now. @gitdex let us know if you still have any issues.
