### ISSUE TITLE
Upload freeze on one pic. ˆC (ctrl-C) allows upload of remaining pics

### ISSUE THREAD

**Issue by oPromessa** [trickortweak/flickr-uploader#61]
Congrats!
----------

Great tool! Thanks! Great job!

Upload freeze on one pic. ˆC (Ctrl-C) allows upload of remaining pics
-------------------------------------------------------------
While uploading it freezes (for several hours) while uploading one particular file once every 100 or so files (nothing special about that file  and similar to so many others).

I then hit ˆC which interrupts the file upload and it them moves normally to the next one.

Any idea how to:
a) either get more feedback from the actual upload process, error message, debug info, etc?
b) set a timeout to continue with the rest of the upload?

Side Note: I don't think I've hit any limits as per flickr.people.getUploadStatus as I only have 243 calls in the last 24 hours.

Thanks for all of your support!

Output sample:
---------------
(edited output to remove special characters '<'and '>'
(...)
Successfully uploaded the file: /volume1/photo/Family.Album/1970-04-20.jpg
Uploading /volume1/photo/Family.Album/1970-06-21-1.jpg...
^C(type 'exceptions.KeyboardInterrupt', KeyboardInterrupt(), traceback object at 0x7f84dbb57c68)
Uploading /volume1/photo/Family.Album/1970-06-21-2.jpg...
Successfully uploaded the file: /volume1/photo/Family.Album/1970-06-21-2.jpg
(...)

**Comment by lodoss5** [comment]
Hi, I never experienced such issue and I am sorry to say I don't have time to search how to implement a timeout.

**Comment by oPromessa** [comment]
@lodoss5 Thanks for your prompt feedback! Weird!

I'll look around for some way to get some more logging info...

Thanks for your help.

**Comment by Grinderz** [comment]
have same issue, fix it, now testing, soon do pull request and more detailes.

**Comment by oPromessa** [comment]
@Grinderz Super!

**Comment by Grinderz** [comment]
test it please https://github.com/trickortweak/flickr-uploader/pull/62

**Comment by oPromessa** [comment]
Great job!

1. Performing initial tests. Will run a larger test shortly.
1. Question: the replacePhoto function *does* not update the tags if they have changed?
1. Meanwhile found a small problem with the replacePhoto arguments. It is called without the oldFileMd5 argument. Log error below. Changed the code to attempt a fiz and testing...

From: `self.replacePhoto(file, row[4], fileMd5, last_modified, cur, con);`

To: `self.replacePhoto(file, row[1], row[4], fileMd5, last_modified, cur, con);`

```
--------- Start time: Wed Aug 31 11:45:49 2016 ---------
Setting up the database: flickrdb
Completed database setup
*****Removing empty Sets from DB*****
*****Completed removing empty Sets from DB*****
*****Adding Flickr Sets to DB*****
*****Completed adding Flickr Sets to DB*****
*****Uploading files*****
Found 265 files
   100 files processed (uploaded, md5ed or timestamp checked)
   200 files processed (uploaded, md5ed or timestamp checked)
Traceback (most recent call last):
  File "uploadr.py", line 1130, in <module>
    flick.upload()
  File "uploadr.py", line 375, in upload
    success = self.uploadFile(file)
  File "uploadr.py", line 557, in uploadFile
    self.replacePhoto(file, row[4], fileMd5, last_modified, cur, con);
TypeError: replacePhoto() takes exactly 8 arguments (7 given)

```

**Comment by Grinderz** [comment]
> Question: the replacePhoto function does not update the tags if they have changed?
update checksum tag only, no handle for others

> Meanwhile found a small problem with the replacePhoto arguments. It is called without the oldFileMd5 argument. Log error below. Changed the code to attempt a fix and testing..
ahh my missed, thanks, fixed.

**Comment by Grinderz** [comment]
last upload near 13000 files, has 95 different exceptions, all handle correct,
do big test only on upload function, replace function tested on one file.
