### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by haphaeu** [trickortweak/flickr-uploader#64]
Hi,
great code, really neat way to back-up my nearly 20 yrs of photos. Thanks!

I'm using it in windows, just had to change very few lines where the linux fcntl module is used. Rather than that small change, the rest runs fine. Can make a PR if that is of interest...

**Comment by antoinerousseau** [comment]
@haphaeu that would be great to have a Windows version, could you make that PR? :)

**Comment by oPromessa** [comment]
Try this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als]o(https://pypi.org/project/flickr-uploader/). It should run on Windows.

**Comment by oPromessa** [comment]
Thanks for the thumbs up! Closing this topic. Let us know if you have any further queries.
