### ISSUE TITLE
try-except catches ctrl-c

### ISSUE THREAD

**Issue by oleander** [trickortweak/flickr-uploader#66]
Current version doesn't allow for `ctrl-c` as `KeyboardInterrupt` is being caught. I suggest reimplementing the current catch-all-statements to only handle the intended exceptions.

**Comment by ManuCart** [comment]
I use ```ctrl-z``` and it's working
But after that when I run again the script it's say allready running
What's wrong

**Comment by oPromessa** [comment]
When you press Ctrl-Z you are actually suspending the process not actually killing it. The process is suspended *on the background*.

You can see that by typing the command `jobs `on the terminal window.

If you can kill the process you need to type use either one of the commands `kill %1 `to kill the 1st process suspended. Beware you can have more processes running/stopped in background and you use %1, %2, %3, etc... to reference to them.

More info on: http://superuser.com/questions/262942/whats-different-between-ctrlz-and-ctrlc-in-unix-command-line

**Comment by oPromessa** [comment]
Ctrl-C is not caught and so it is working on this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als]o(https://pypi.org/project/flickr-uploader/).

**Comment by oPromessa** [comment]
I'm closing this topic. @oleander and @ManuCart let us know should you have any further queries.
