### ISSUE TITLE
Photos not deleted on Flickr after new installation flickr-uploader script on new computer

### ISSUE THREAD

**Issue by ManuCart** [trickortweak/flickr-uploader#72]
Everything in the title.

Do I need copy the db file?

**Comment by lodoss5** [comment]
Yes you need to copy the db file.

**Comment by ManuCart** [comment]
Ok thanks, this what I'm thinking.
But now because I just made a new installation on new computer, I loose my old db file.
Do you know a way to delete every photos on flickr

**Comment by lodoss5** [comment]
Go to Flickr and delete them. This is only way so far.

**Comment by ManuCart** [comment]
Ok Thanks
