### ISSUE TITLE
Windows\Cygwin\Python error

### ISSUE THREAD

**Issue by qzcw** [trickortweak/flickr-uploader#76]
Hello.

I tried to run your script on my Windows PC, but it failed do to what appears to be the fcntl-library problem on Windows machines.

So, then I installed Cygwin Linux emulator on Windows with Python installed on it. Now, when trying to run the uploadr script there is not anymore fcntl error message, but instead this:

```bash
$ python uploadr.py
--------- Start time: Mon Dec 12 16:19:21 2016 ---------
False
Setting up the database: flickrdb
Completed database setup
Getting new token
(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)
Error: cannot get frob:(<type 'exceptions.TypeError'>, TypeError('expected string or buffer',), <traceback object at 0x6ffff966cb0>)
Traceback (most recent call last):
  File "uploadr.py", line 1167, in <module>
    flick.authenticate()
  File "uploadr.py", line 169, in authenticate
    self.getAuthKey()
  File "uploadr.py", line 208, in getAuthKey
    "frob": FLICKR["frob"],
KeyError: 'frob'
```

**Comment by haphaeu** [comment]
it is an easy fix to get it running in windows. see
https://github.com/trickortweak/flickr-uploader/pull/75

**Comment by oPromessa** [comment]
Try this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) and also available [on pypi.org als]o(https://pypi.org/project/flickr-uploader/). It should run on Windows.

**Comment by oPromessa** [comment]
@qzcw if you don't want to go with this fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) the last pull request #92 adds Windows compatibility.

Closing this issue. Let us know if you have any more queries.
