### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Jeeosch** [trickortweak/flickr-uploader#83]
I got the following feedback from task scheduler when running the latest version (31-01-2017) of the flickr-uploader python script on my NAS (Synology DS214play, DSM 6.1-15047 Update 1):

> Task: Flickr Uploader
Start time: Wed, 15 Mar 2017 02:30:02 GMT
Stop time: Wed, 15 Mar 2017 02:30:08 GMT
Current status: 1
Standard output/error:
--------- Start time: Wed Mar 15 02:30:03 2017 ---------
False
Setting up the database: /usr/bin/FlickrUploader/flickrdb
Completed database setup
*****Removing empty Sets from DB*****
*****Completed removing empty Sets from DB*****
*****Adding Flickr Sets to DB*****
*****Completed adding Flickr Sets to DB*****
*****Uploading files*****
Traceback (most recent call last):
 File "/usr/bin/FlickrUploader/uploadr.py", line 1200, in <module>
   flick.upload()
 File "/usr/bin/FlickrUploader/uploadr.py", line 376, in upload
   allMedia = self.grabNewFiles()
 File "/usr/bin/FlickrUploader/uploadr.py", line 465, in grabNewFiles
   for dirpath, dirnames, filenames in os.walk(unicode(FILES_DIR), followlinks=True):
 File "/usr/lib/python2.7/os.py", line 286, in walk
   if isdir(join(top, name)):
 File "/usr/lib/python2.7/posixpath.py", line 73, in join
   path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

Can somebody give a hint what the cause might be?
Many thanks in advance!

**Comment by oPromessa** [comment]
Hi there. You probably have some directories or filenames with international characters.
I had similar issues and made a [PULL Request (#80)](https://github.com/trickortweak/flickr-uploader/pull/80) which is pending. This version also updates the time/date on Video files once they are uploaded to flickr.

Try with that version. 
I have an updated version with more corrections but I have still not uploaded it for lack of time.

All the best.

**Comment by Jeeosch** [comment]
Hi!

Many thanks for the hint!

For now I wait for the next "stable" version.
I am using the version issued on 27/06/2015 since that worked fine, so far.

But maybe I give PULL request #80 a try ... ;-)

Best regards,


Georg

**Comment by Jeeosch** [comment]
I just tried the version you created (PULL request #80) and it seems to work.
I'll wait for a complete cycle and let you know!
Many thanks for now!

**Comment by oPromessa** [comment]
Just updated pull request #80 with the latest UTF international characters handling.

Try it out.

**Comment by oPromessa** [comment]
Stable [version 2.8.7 available on Pypi.org](https://pypi.org/project/flickr-uploader/)

**Comment by oPromessa** [comment]
I'm closing this topic due to lack of activity. @Jeeosch let us know should you have any further queries.
