### ISSUE TITLE
Upload from multiple folders

### ISSUE THREAD

**Issue by qzcw** [trickortweak/flickr-uploader#87]
Is it possible to include multiple folders as the upload source? 
I have lots of photos across multiple external hard disks, so I can't include them all in a one folder only.

**Comment by oPromessa** [comment]
Hello qzcw,

You can use links to create a virtual directory tree all under the same folder to use with the uploadr. 

If you have your photo folders:
- on unix or on your DSM you can use the "ln -s" command to create symbolic links (check the web how to use and I've also answered on another message on this topic.
- on windows you can also create links to folders on other disks on window 7 and above. Do search a bit on the web for instructions. 

Thanks!

**Comment by oPromessa** [comment]
Closing this topic.  @qzcw, let us know in case it's not solved.
