### ISSUE TITLE
permission denied.

### ISSUE THREAD

**Issue by norayr** [trickortweak/flickr-uploader#89]
every time i run it, the browse window opens, and flickr page with 'permission denied' shows up.
i am logged in to flickr in that browser, key and api are set correctly.

**Comment by oPromessa** [comment]
Don't know if you've been using this tool for some time now or if you're just trying it out...

### Forked new tool **oPromessa/flickr-uploader**
In case you want to give it a try... I had to fork this tool to make it work with the new OAuth-based authentication method of **flickr.com**:
- [This GituHub repository oPromessa/flickr-uploader](https://github.com/oPromessa/flickr-uploader)
- [And the latest release is 2.8.6 ](https://github.com/oPromessa/flickr-uploader/releases/tag/2.8.6)
- [And also available via pypi.python.org on this link](https://pypi.org/project/flickr-uploader)

Which includes:
- New Authentication for flickr.
- Use of flickrapi.
- Multiprocessing to achieve speedy and parallel uploads. Marvelous for 59K photos Library like mine.
- A bunch of new options
- Setup instructions for Synology
- and much more

### **Do read the README.md**

Enjoy! I've applied to a secondary account on flickr.com for testing. You can also do that!

**Comment by oPromessa** [comment]
I'm closing this topic due to lack of activity. @norayr let us know should you have any further queries.
